<script src="{{$app->request->get('api_shortname')}}/js/jquery.js"></script>
<script src="{{$app->request->get('api_shortname')}}/js/waypoints.js"></script>
<script src="{{$app->request->get('api_shortname')}}/js/modernizr.js"></script>
<script src="{{$app->request->get('api_shortname')}}/js/bootstrap.bundle.min.js"></script>
<script src="{{$app->request->get('api_shortname')}}/js/meanmenu.js"></script>
<script src="{{$app->request->get('api_shortname')}}/js/swiper-bundle.js"></script>
<script src="{{$app->request->get('api_shortname')}}/js/slick.js"></script>
<script src="{{$app->request->get('api_shortname')}}/js/magnific-popup.js"></script>
<script src="{{$app->request->get('api_shortname')}}/js/counterup.js"></script>
<script src="{{$app->request->get('api_shortname')}}/js/wow.js"></script>
<script src="{{$app->request->get('api_shortname')}}/js/nice-select.js"></script>
<script src="{{$app->request->get('api_shortname')}}/js/tilt.jquery.min.js"></script>
<script src="{{$app->request->get('api_shortname')}}/js/isotope-pkgd.js"></script>
<script src="{{$app->request->get('api_shortname')}}/js/imagesloaded-pkgd.js"></script>
<script src="{{$app->request->get('api_shortname')}}/js/ajax-form.js"></script>
<script src="{{$app->request->get('api_shortname')}}/js/headline.js"></script>
<script src="{{$app->request->get('api_shortname')}}/js/main.js"></script>
<script src="{{$app->request->get('api_shortname')}}/js/jquery-3.6.0.min.js"></script>
<!-- <script src="{{$app->request->get('api_shortname')}}/js/form1.js"></script>
<script src="{{$app->request->get('api_shortname')}}/js/form2.js"></script> -->
<script src="{{$app->request->get('api_shortname')}}/js/forms.js"></script>