<script src="js/jquery.js"></script>
<script src="js/waypoints.js"></script>
<script src="js/modernizr.js"></script>
<script src="js/bootstrap.bundle.min.js"></script>
<script src="js/meanmenu.js"></script>
<script src="js/swiper-bundle.js"></script>
<script src="js/slick.js"></script>
<script src="js/magnific-popup.js"></script>
<script src="js/counterup.js"></script>
<script src="js/wow.js"></script>
<script src="js/nice-select.js"></script>
<script src="js/tilt.jquery.min.js"></script>
<script src="js/isotope-pkgd.js"></script>
<script src="js/imagesloaded-pkgd.js"></script>
<script src="js/ajax-form.js"></script>
<script src="js/headline.js"></script>
<script src="js/main.js"></script>
<script src="js/jquery-3.6.0.min.js"></script>
<!-- <script src="js/form1.js"></script>
<script src="js/form2.js"></script> -->
<script src="js/forms.js"></script>